### ISSUE TITLE
1일차 관계형 데이터베이스 개념

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#132]
- 데이터베이스를 사용하는 이유
- 관계형 데이터베이스의 개념과 장단점
- DML, DDL, DCL
- Key
- Join

**Comment by sunH0** [comment]
- 관계형 데이터 베이스의 장단점
-  데이터 베이스 Key에는 무엇이 있나요?
- Join에 대해서 설명해주세요?
- DML,DCL, DDL은 무엇인가요?
