### ISSUE TITLE
2일차 Sharding&Master/Slave, 이상 현상과 정규화

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#133]

**Comment by sunH0** [comment]
1. Sharding을 왜 적용해야 하나요?
2. 이상현상은 무엇인가요?
3. 반 정규화는 무엇이고 어떤 경우 필요하나요?
4. 데이터 베이스에서 master-slave 구조는 무엇을 의미하나요?
5. 샤딩과 수평 파티셔닝은 차이가 있나요?
