### ISSUE TITLE
[운영체제] 4일차 CPU 스케줄링

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#14]
- CPU 스케줄링
	  - 장기 스케줄링
	  - 중기 스케줄링
	  - 단기 스케줄링

**Comment by pinoa1228** [comment]
1. 스왑 아웃은 어떤 프로세스를 대상으로 동작하나요
2. cpu 스케줄링에 대해 설명해 보세요
3. 스케줄링이 이루어지는 시점에 대해 설명해 보세요
4. 스케줄링 기법에 대해 설명해 보세요

**Comment by locodingve** [comment]
1. CPU 스케줄링이란 무엇인가요?
2. CPU 스케줄링은 언제 발생하나요?
3. long term scheduling, medium term scheduling, short term scheduling 의 차이점을 설명해 주세요.
4. medium scheduling에서 suspended 상태와 blocked 상태가 어떤 점이 다른지 설명해 주세요.

**Comment by sunH0** [comment]
1.  CPU 스케쥴링이란?
2.  CPU 스케쥴링은 언제 발생하나요?
3. 프로세스 스케쥴링의 long term, short term, medium term 세 유형 차이를 설명해주세요.
4. 프로세스를 스케줄링하기 위한 3가지 Queue 에 대해 설명해주세요

**Comment by seung-hun-h** [comment]
1. 프로세스 스케줄링?
2. 스케줄링 단계에 대해서 설명
3. 다중 큐를 사용하는 이유(준비 큐, 대기 큐)
4. CPU 작업이 많은 프로세스와 입출력 작업이 많은 프로세스 중 어느 프로세스를 먼저 실행할 것인가?
5. 선점형 비선점형 스케줄링에 대해서 설명

**Comment by hanjo8813** [comment]
<details>
    <summary><b>스케줄러(스케줄링)의 종류에 대해 설명해주세요</b></summary>
    <br>
    스케줄러란 어떤 프로세스에게 자원을 할당할지 선택하는 커널 모듈입니다.<br>
    스케줄러는 장기, 중기, 단기 스케줄러 세가지 종류가 있습니다.<br>
    장기 스케줄러는 준비 큐에 넣을 프로세스를 선택하는 스케줄러로, 한정된 메모리에서 한번에 많은 프로세스가 올라오게 되면 프로세스를 임시로 디스크에 저장합니다.<br>
    중기 스케줄러는 메모리에 적재된 프로세스 수를 관리하는 스케줄러로, 메모리에 프로세스가 너무 많아질 경우 준비나 대기상태의 프로세스 메모리를 빼앗아 디스크로 swap out합니다.<br>
    단기 스케줄러는 CPU 스케줄러라고 불리며 준비 큐에서 CPU를 할당할 프로세스를 선택하는 역할을 합니다.
</details>

<br>

<details>
    <summary><b>CPU 스케줄링에 대해 설명해주세요</b></summary>
    <br>
    CPU 스케줄링이란 준비 큐에 있는 프로세스를 스케줄링 알고리즘을 통해 선택하여 CPU를 할당하는 작업을 말합니다.<br>
    빈번히 일어나는 프로세스의 CPU 교체 과정에서 CPU 이용률을 최대화하기 위해 사용됩니다.
</details>

<br>

<details>
    <summary><b>CPU 스케줄링의 발생 시점에 대해 설명해주세요</b></summary>
    <br>
    CPU 스케줄링은 네가지 상황에서 발생합니다.<br>
    인터럽트가 발생되어 프로세스가 실행상태에서 준비상태로 변경될 때, 실행상태의 프로세스가 종료될때, 실행상태의 프로세스가 입출력이 발생하여 대기 상태로 변경될 때, 대기상태의 프로세스가 입출력 작업이 완료되어 준비상태로 변경될 때 CPU 스케줄링이 발생하게 됩니다.
</details>

<br>

<details>
    <summary><b>CPU 스케줄링 종류에 대해 설명해주세요</b></summary>
    <br>
    CPU 스케줄링의 종류는 선점 방식과 비선점 방식 두가지가 있습니다.<br>
    선점 방식은 프로세스가 CPU를 점유하고 있어도 운영체제가 강제로 CPU를 빼앗을 수 있는 방식입니다.<br>
    따라서 우선순위가 높은 프로세스를 빠르게 실행할 수 있는 장점이 있어 실시간 응답 시스템에 적합하지만, 잦은 CPU 교체로 인한 문맥교환 발생으로 오버헤드가 발생하는 단점도 존재합니다.<br>
    비선점 방식은 프로세스가 CPU를 점유하고 있을때 이를 빼앗을 수 없는 방식입니다.<br>
    따라서 문맥교환이 자주 발생하지 않아 응답시간 예측이 쉽고, 일괄처리 시스템에 적합하지만, 빠르게 처리해야 하는 프로세스가 있어도 계속 대기해야 하는 단점이 있습니다.
</details>

**Comment by neilsonT** [comment]
1. 스케줄링에 대해 설명해주세요
2. 스케줄링은 언제 발생하나요?
3. 선점형과 비선점형 스케줄링에 대해 비교해서 설명해주세요
4. 장기, 중기, 단기 스케줄링을 설명해주세요
