### ISSUE TITLE
[운영체제] 5일차 스케줄링 알고리즘

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#15]
- 스케줄링 알고리즘
	  - FCFS
	  - SJF
	  - Round Robin
	  - SRT
	  - Priority scheduling
	  - Multilevel Queue
	  - Multilevel Feedback Queue

**Comment by seung-hun-h** [comment]
1. 스케줄링 알고리즘에 대해 설명해주세요
2. 콘보이(호위) 효과에 대해 설명해주세요
3. 아사 현상과 그 해결 방법에 대해 설명해주세요
4. 우선순위 역전에 대해 설명해주세요
5. 멀티 레벨 피트백 큐를 I/O Burst와 CPU Burst를 연관지어 설명해주세요

**Comment by locodingve** [comment]
1. starvation 현상에 대해 설명해 주세요.
2. 스케줄링 기법을 각각 간단하게 설명해 주세요.
3. FCRS 스케줄링을 개선한 스케줄링 방식에 대해 설명해 주세요.
4. Round Robin 스케줄링 방식에서 time quantum 설정에 따른 겨로가를 설명해 주세요.

**Comment by sunH0** [comment]
1. 비선점 방식 스케줄링 알고리즘에 대해 설명해주세요
2. Multi Level Queue와 Multilevel-Feedback-Queue 알고리즘을 비교해서 설명해주세요
3. 우선순위 큐의 문제점에 대해서 설명해주세요.
4. SJF 알고리즘은 선점 방식일까요 비선점방식일까요?

**Comment by neilsonT** [comment]
1. SJF알고리즘은 어떤 시스템에 적합할까요?
2. 에이징 기법은 무엇인가요?
