### ISSUE TITLE
[운영체제] 2일차 프로세스

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#2]
- 프로세스
	  - 프로세스 개념
	  - 프로세스 상태
	  - 프로세스 제어 블록
	  - 프로세스 문맥 교환

**Comment by locodingve** [comment]
1. context switching 이란 무엇인가요?
2. 프로세스와 프로그램의 차이점은 무엇인가요?
3. 인터럽트가 무엇인가요?
4. 프로세스 상태를 설명해 주시겠습니까?

참고사항 : 관련 질문에 대한 답변은 저의 Pr에  따로 기록될 예정입니다. 필요시 참고하세요~ ㅎㅎ

**Comment by neilsonT** [comment]
1. 프로세스가 뭔가요?
2. 프로세스의 상태와 상태가 변하는 과정에 대해 설명해주세요
3. PCB에 대해 설명해주세요
4. Context Switch가 뭔가요??

**Comment by pinoa1228** [comment]
- 프로세스 상태 변화에 대해 설명하세요
- 프로세스와 프로그램 차이에 대해 설명하세요
- Context Switching이란?
- 프로세스 제어 블록(pcb)에대해 설명해 보세요
- 대기상태의 필요성에대해 설명해 보세요

**Comment by hanjo8813** [comment]
<details>
    <summary><b>프로세스에 대해 설명해주세요</b></summary>
    <br>
    프로세스는 실행상태의 프로그램을 뜻합니다.<br>
    프로그램이 실행되면 자원이 할당되고, 프로세스로 전환되며 독립적인 메모리 구조를 가지게 됩니다.<br>
    프로세스의 메모리 구조는 코드, 데이터, 힙, 스택 영역으로 나뉩니다.<br>
    코드 영역은 컴파일된 실행 가능한 코드가 저장되는 영역이고, 데이터 영역은 전역 및 정적 변수가 저장되는 영역입니다.<br>
    스택 영역은 매개변수, 지역변수, 리턴 값 등이 저장되는 영역이며, 컴파일시 크기가 결정됩니다.<br>
    힙 영역은 동적 메모리를 할당 및 해제할 수 있는 영역이며, 런타임시 크기가 결정됩니다.
</details>

<br>

<details>
    <summary><b>프로세스 상태 변화에 대해 설명해주세요</b></summary>
    <br>
    프로세스의 상태로는 생성, 준비, 실행, 대기, 종료 상태가 있습니다.<br>
    프로세스가 생성되면 생성 상태가 되고, 바로 준비 상태로 변경됩니다.<br>
    이 때 준비 대기열큐에 해당 프로세스가 추가되고, CPU 스케줄러가 준비 큐에서 우선순위가 높은 프로세스를 실행 상태로 변경시킵니다.<br>
    실행 상태의 프로세스는 CPU 자원을 할당 받아 작업을 수행하게 되고, 모든 작업이 끝나면 종료 상태로 변경됩니다.<br>
    만약 프로세스 실행 중 이벤트나 입출력 요청이 발생한다면 해당 프로세스는 잠시 대기 상태로 변경되고, 이벤트가 완료되었을 때 다시 준비 상태가 됩니다.
</details>

<br>
    
<details>
    <summary><b>PCB에 대해 설명해주세요</b></summary>
    <br>
    프로세스 제어 블록은 커널의 데이터 공간에 존재하는 프로세스 정보를 저장하는 자료구조입니다.<br>
    프로세스가 실행 상태에서 준비 상태로 변경될 때 프로세스의 작업 진행 상황을 저장해놓지 않으면 해당 프로세스가 다시 실행상태가 되었을 때 처음부터 작업을 실행해야 합니다.<br>
    따라서 프로세스가 실행될 때 작업 진행상황을 지속적으로 프로세스 제어 블록에 저장하여 프로세스 상태가 변경되어도 마지막 작업 지점부터 시작할 수 있도록 해줍니다.
</details>

<br>

<details>
    <summary><b>문맥교환에 대해 설명해주세요</b></summary>
    <br>
    문맥교환은 CPU 제어권이 다른 프로세스로 이양되는 과정을 뜻합니다.<br>
    예를 들어 프로세스가 대기 상태로 변경될 때 준비 상태의 프로세스로 CPU 제어권이 변경되게 됩니다.<br>
    이 때 문맥교환이 발생하며 대기 상태로 변경된 프로세스의 문맥을 PCB에 저장하고, 새로 실행된 프로세스의 PCB에서 문맥을 복원시킵니다.<br>
    여기서 문맥교환에 필요한 시간과 메모리를 오버헤드라 부릅니다.
</details>

<br>

**Comment by seung-hun-h** [comment]
1. 프로그램과 프로세스의 차이에 대해서 설명해주세요
2. 폰 노이만 구조에 대해서 설명해주세요
3. 프로세스 문맥 교환에 대해 설명해주세요
4. 프로세스의 구조에 대해서 설명해주세요(코드, 데이터, 스택 영역)
5. 프로세스 상태 천이에 대해서 설명해주세요

**Comment by sunH0** [comment]
1. 프로세스와 프로그램의 차이는 무엇이 있을까요?
2. 프로세스의 메모리 구조에 대해서 설명해주세요.
3. 문맥교환이 발생하는 시점에 대해서 설명해주세요.
4. PCB 에 대해서 설명해주세요.
5. 프로세스의 상태에 대해서 설명해주세요.
