### ISSUE TITLE
[운영체제] 3일차 스레드

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#3]
- 스레드
	  - 스레드 개념
	  - 멀티스레드의 구조
	  - 멀티스레드의 장단점
	  - 멀티 프로세스 VS 멀티 스레드

**Comment by locodingve** [comment]
1. 프로세서의 힙, 스택 영역에는 어떤 정보가 있나요?
2. 스택을 스레드 마다 독립적으로 할당하는 이유가 무엇인가요?
3. 멀티스레드의 장단점을 설명해주세요.
4. 멀티스레드와 멀티프로세스의 차이를 설명해 주세요.

**Comment by neilsonT** [comment]
1. 스레드의 개념에 대해 설명해주세요.
2. 멀티 스레드의 구조에 대해 설명해주세요.
3. 왜 스택만 따로 분리해서 사용하나요?
4. 멀티 스레드의 장단점을 설명해주세요
5. 멀티 프로세스와 멀티 스레드를 비교해서 설명해주세요

**Comment by sunH0** [comment]
1. 스택 영역을 스레드마다 독립적으로 할당하는 이유에 대해 설명해 주세요.
2.  멀티 스레드의 장단점을 설명해주세요.
3. 스레드의 구조에 대해 설명해주세요.
4. 멀티 프로세스와 멀티 스레드의 차이를 설명해주세요.
5. 스레드 풀에 대해서 설명해주시요.

**Comment by seung-hun-h** [comment]
1. 프로세스와 스레드르 비교하여 설명해주세요
2. 멀티스레드의 장단점을 설명해주세요
3. 스레드마다 독립적으로 할당하는 영역과 그 이유에 대해서 설명해주세요
4. 멀티 스레드 모델에 대해서 설명해주세요(사용자, 커널, 멀티 레벨 스레드)
5. 멀티프로세스와 멀티스레드를 비교하여 설명해주세요

**Comment by hanjo8813** [comment]
<details>
    <summary><b>스레드에 대해 설명해주세요</b></summary>
    <br>
    스레드는 프로세스의 실행 단위로, 프로세스는 최소 하나 이상의 스레드를 가집니다.<br>
    하나의 프로세스가 수행해야 하는 작업을 스레드가 나누어 수행함으로써 프로세스의 처리 속도를 높이는 역할을 합니다.<br>
    스레드는 프로세스의 코드, 데이터, 힙 영역을 공유하고, 레지스터 및 스택 영역은 각 스레드마다 따로 할당 받습니다.<br>
    각 스레드가 메모리 공간을 공유하기 때문에 스레드간 통신 비용이 적어 문맥교환에 용이합니다.
</details>

<br>

<details>
    <summary><b>프로세스와 스레드의 차이에 대해 설명해주세요</b></summary>
    <br>
    프로세스는 실행중인 프로그램을 뜻하며 독립된 메모리 영역을 가져 프로세스는 서로 침범할 수 없습니다.<br>
    스레드는 프로세스의 실행 단위로 프로세스 메모리 영역 중 스택 영역을 제외한 부분을 공유합니다.
</details>

<br>

<details>
    <summary><b>멀티 프로세스와 멀티 스레드의 차이에 대해 설명해주세요</b></summary>
    <br>
    멀티 프로세스는 하나의 프로그램을 여러개의 프로세스로 구성하는 것으로, 프로세스는 독립된 메모리 영역을 가지고 서로 침범할 수 없습니다.<br>
    멀티 스레드는 하나의 프로세스가 여러개의 스레드로 구성하는 것을 뜻하며 프로세스 내부에서 메모리를 공유합니다.<br>
    이와 같은 자원공유 여부의 차이때문에 멀티 프로세스는 한 프로세스에 문제가 생겨도 다른 프로세스에는 영향을 끼치지 않지만, 멀티 스레드는 한 스레드가 문제가 생기면 프로세스 전체에 영향을 끼치게 되며 동기화 문제가 발생할 수 있습니다.<br>
    하지만 멀티 스레드의 경우 문맥 교환이 발생했을 때 스택 영역만 변경하면 되기에 오버헤드가 적게 발생하는 반면, 멀티 프로세스의 경우 메모리 영역 초기화 작업이 일어나기 때문에 오버헤드가 크게 발생합니다.
</details>
