### ISSUE TITLE
[운영체제] 6일차 인터럽트

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#33]

**Comment by locodingve** [comment]
1. 인터럽트 처리과정은 어떻게 이루어지나요?
2. 인터럽트란 무엇인가요?
3. 동기적 인터럽트와 비동기적 인터럽트가 무엇인가요?

**Comment by neilsonT** [comment]
1. 이중모드가 무엇인가요?
2. DMA에 대해 설명해주세요
3. 인터럽트는 왜 필요한가요?

**Comment by seung-hun-h** [comment]
1. 인터럽트에 대해 설명해주세요
2. 인터럽트 벡터에 대해 설명해주세요
3. 인터럽트 처리 과정에 대해 설명해주세요
4. DMA에 대해 설명해주세요
