### ISSUE TITLE
[운영체제] 7일차 프로세스 동기화

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#34]

**Comment by neilsonT** [comment]
1. 운영체제에서 경쟁 상태가 무엇인가요?
2. 임계 구역은 무엇이고 여기서 발생하는 문제를 해결하기 위한 조건은 뭐가 있죠?
3. 상호배제를 구현하는 알고리즘은 어떤 것들이 있나요?
4. 피터슨 알고리즘은 무엇이고 어떤 문제점이 있나요?
5. 세마포어에 대해 설명해주세요

**Comment by seung-hun-h** [comment]
1. 공유 자원과 경쟁 상태에 대해서 설명해주세요
2. 임계 구역을 해결하기 위한 방법은 어떤 것들이 있나요?
3. 모니터에 대해서 설명해주세요

**Comment by pinoa1228** [comment]
1. 세마포어와 뮤텍스의 차이점은 무엇인가요
2. 피터슨 알고리즘은 무엇인가요

**Comment by locodingve** [comment]
1. 임계영역이란 무엇인가요?
2. 프로세스 동기화란 무엇인가요?
3. 상호배제란 무엇인가요?
4. 모니터란 무엇이며, 동작원리를 간단하게 알려주세요.
5. 뮤텍스와 세마포어 차이는 무엇인가요?

**Comment by sunH0** [comment]
1. 세마포어와 뮤텍스의 차이점은 무엇일까요?
2. 피터슨 알고리즘 의 단점?
3. 임계구역은 무엇이고 해결하기 위한 조건?
4. 스핀락과 세마포어의 차이점
