### ISSUE TITLE
[운영체제] 8일차 교착상태

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#35]

**Comment by sunH0** [comment]
1. 식사하는 철학자 문제를 해결하는 방법을 설명해 주세요.
2. 기아 상태와 교착 상테의 차이점을 설명해주세요
3. 교착 상태 검출에 대해 설명해주세요
4. 교착상태에 대해서 발생 조건과 같이 설명해주세요

**Comment by locodingve** [comment]
1. 데드락이 무엇인가요?
2. 데드락의 발생 조건은 무엇인가요?
3. 데드락 해결방법은 무엇이 있나요?

**Comment by seung-hun-h** [comment]
1. 식사하는 철학자 문제를 정의하고 해결 방법에 대해 설명해주세요
2. 데드락의 발생 조건에 대해 설명해주세요
3. 데드락의 해결 방법에 대해 설명해주세요
