### ISSUE TITLE
[운영체제] 9일차 메모리 관리

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#36]

**Comment by locodingve** [comment]
1. 단편화(fragmentation)란 무엇인가요?
2. 고정 분할 방식(FPM) 과 가변 분할 방식(VPM) 에 대해 설명해 주세요.
3. VPM의 배치 전략을 설명해주세요.
4. VPM은 external fragmentation을 어떻게 해결하는가요?
5. 메모리 관리란 무엇이며, 필요성을 설명해 주세요.

**Comment by seung-hun-h** [comment]
1. 32bit CPU와 64bit CPU에 대해 설명해주세요
2. 절대 주소와 상대 주소에 대해 설명해주세요
