### ISSUE TITLE
[운영체제] 11일차 가상메모리 관리

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#38]

**Comment by neilsonT** [comment]
1. 페이지 폴트란 무엇인가요?
2. 페이지 교체 알고리즘에서 FIFO에 대해 설명해주세요
3. LRU에 대해 설명해주세요.

**Comment by pinoa1228** [comment]
1. 페이지 교체 알고리즘이 필요한 이유는 무엇인가요?
2. 요구페이징을 하는 이유는 무엇인가요?

**Comment by locodingve** [comment]
1. 페이지 폴트란 무엇인지 설명해주세요.
2. 페이지를 교체하는 다양한 방법들에 대해 알려주세요.
3. 리눅스 운영체제에서는 어떤 페이지 교체 알고리즘을 사용할까요? 자신이 생각하는 이유와 함께 알고리즘을 설명해주세요.

**Comment by hanjo8813** [comment]
<details>
    <summary><b>요구 페이징에 대해 설명해주세요</b></summary>
    <br>
    요구 페이징이란 초기에는 필요한 페이지만을 메인메모리에 적재하고, 프로세스 실행중에 실제로 필요한 페이지를 적재하는 기법입니다.<br>
    이로써 메모리 공간을 절약할 수 있고, 프로세스의 응답 속도가 향상되는 장점을 가집니다.<br>
    하지만 페이지 부재가 발생하는 단점도 존재합니다.
</details>

<br>

<details>
    <summary><b>페이지 부재에 대해 설명해주세요</b></summary>
    <br>
    페이지 부재란 프로세스에게 필요한 페이지가 메인메모리의 프레임 공간에 없을 때 발생하게 됩니다.<br>
    페이지 부재가 발생하면 메인메모리에 필요한 페이지를 가져와야 하는데, 만약 프레임 공간이 부족하다면 특정 프레임을 다시 디스크 스왑영역으로 내보내야 합니다.<br>
    이 때 페이지 교체 알고리즘을 사용하여 적절한 프레임을 내보내게 되고, 페이지 테이블에서 가상메모리 주소를 확인 후 필요한 페이지를 메민메모리에 가져오게 됩니다.
</details>

<br>

<details>
    <summary><b>페이지 교체 알고리즘에 대해 설명해주세요</b></summary>
    <br>
    페이지 부재가 발생하여 페이지를 가져올 메인메모리의 프레임 공간이 부족할 경우 프레임을 교체해야하는데, 이 때 가장 적절한 프레임을 선택하는 알고리즘입니다.<br>
    페이지 교체 알고리즘의 종류로는 FIFO, LRU, NRU 등이 있습니다.
</details>

<br>

<details>
    <summary><b>FIFO에 대해 설명해주세요</b></summary>
    <br>
    가장 먼저 들어온 페이지를 교체하는 알고리즘입니다.<br>
    페이지가 들어온 순서대로 저장해야하기 때문에 큐로 구현이 가능합니다.
</details>

<br>

<details>
    <summary><b>LRU에 대해 설명해주세요</b></summary>
    <br>
    가장 오랫동안 사용하지 않은 페이지를 교체하는 알고리즘입니다.<br>
    큐로 구현이 가능하고 페이지의 사용시간을 지속적으로 기록해야하기 때문에 큰 오버헤드가 발생하는 단점이 있습니다.
</details>

<br>

<details>
    <summary><b>NRU에 대해 설명해주세요</b></summary>
    <br>
    최근에 사용하지 않은 페이지를 교체하는 알고리즘입니다.<br>
    LRU와 비슷하게 동작하고, 적은 오버헤드로 적절한 성능을 낼 수 있습니다.<br>
    참조비트와 변형비트가 사용하여 페이지 참조와 수정을 기록하여 교체 우선순위를 결정합니다.
</details>
