### ISSUE TITLE
[네트워크] 4일차 HTTP

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#75]
- HTTP란?
- HTTP status code
- HTTP methbod

**Comment by neilsonT** [comment]
1. HTTP가 무엇인가요?
2. HTTP 메소드 아는 것 설명해주세요
3. 상태 코드에 대해서 설명해주세요.
4. 멱등성은 무엇인가요?

**Comment by locodingve** [comment]
1. HTTP의 정의를 간단하게 말씀해 주세요.
2. HTTP 특징을 간단하게 말씀해 주세요.(응답코드, 메서드 등등)

**Comment by pinoa1228** [comment]
1. PUT과 PATCH의 차이에 대해 설명해 주세요

**Comment by sunH0** [comment]
1. PUT과 PATCH의 차이에 대해 설명해 주세요.
2. HTTP는 메세지 구조에는 무엇이 있나요?
3. 400 번대 응답 코드에 대해 설명해 주세요.
4. 서버와 클라이언트에 대해 설명해주세요
5. HTTP는 어떤 문제점이 있나요?

**Comment by hanjo8813** [comment]
<details>
    <summary><b>HTTP에 대해 설명해주세요</b></summary>
    <br>
    HTTP는 인터넷에서 데이터를 주고받을 수 있게하는 프로토콜입니다.<br>
    HTTP를 통해서 html, json, xml과 같은 형태의 데이터를 주고받을 수 있게 됩니다.<br>
    HTTP의 특징에는 비연결성과 무상태성이 있습니다.<br>
    비연결성은 클라이언트가 요청을 서버에 보낸 후 서버가 응답하면 연결이 끊어지는 것을 뜻합니다.<br>
    무상태성은 연결을 끊는 순간 클라이언트와 서버의 통신은 끝나며 상태 정보를 유지하지 않는 것을 뜻합니다.
</details>

<br>

<details>
    <summary><b>HTTP method에 대해 설명해주세요</b></summary>
    <br>
    HTTP 메소드는 요청의 목적이나 종류를 나타내는 수단입니다.<br>
    총 9개의 종류가 있으며, 주로 사용되는 메소드는 5가지로 GET, POST, DELETE, PUT, PATCH 가 있습니다.<br>
    GET과 같은 일부 메소드는 여러번 요청한 결과가 한번 요청한 결과와 같은 멱등성을 가집니다. 
</details>

<br>

<details>
    <summary><b>HTTP status code에 대해 설명해주세요</b></summary>
    <br>
    HTTP 상태 코드란 http 요청의 처리 결과를 응답에서 알려주기 위한 정보입니다.<br>
    5가지 종류의 상태 코드가 있고 이는 1xx, 2xx, 3xx 와 같은 형태로 표기합니다.<br>
    1xx 코드는 요청을 받고 처리중인 상태를 뜻하며 현재는 거의 사용되지 않습니다.<br>
    2xx 코드는 요청이 정상 처리된 상태를 의미합니다.<br>
    3xx 코드는 리다이렉션을 수행해야하는 상태이며 location 헤더가 있다면 해당 location 위치로 이동하도록 합니다.<br>
    4xx 코드는 클라이언트측에서 오류가 발생한 상태를 의미하고, 5xx 코드는 서버측에서 오류가 발생한 상태를 의미합니다.
</details>
