### ISSUE TITLE
[네트워크] 5일차 HTTP1.1 VS HTTP2.0

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#76]
- HTTP1.1
- HTTP2.0
- HTTP3.0?

**Comment by sunH0** [comment]
1. HTTP 1.1 의 문제점이 뭐가 있나요??
2. http 2.0은 http 1.1의 문제를 어떻게 개선했나요?
3. http 2.0의 문제점이 있나요??
