### ISSUE TITLE
[네트워크] 6일차 HTTPS & REST API

### ISSUE THREAD

**Issue by seung-hun-h** [seung-hun-h/cs-study-for-interview#77]

**Comment by locodingve** [comment]
1. https 란 무엇이고, 왜 필요한가요?
2.  공통키 암호와 방식과 공개키 암호와 방식을 설명해 주세요.
3. restapi를 간단하게 정의해 주시겠습니까?

**Comment by sunH0** [comment]
1. 프로젝트 경험 중 restful api 구현을 위해서 어떤 노력을 하셨나요?
2. https가 http 보다 보안이 어떻게 향상했나요?
3. https에서 암호키는 어떠한 방식으로 사용되나요?
4. rest api 는 왜 필요할까요?
